In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import matplotlib.dates as dates
import datetime
import time
import csv

In [2]:
'''Testing array indexing with variables'''

test_arr=np.array([[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12]])

print(test_arr)

row_var=2
col_var=3

test_arr[0][1]
test_arr[row_var][1]
test_arr[row_var][col_var]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


12

In [2]:
%%time
df_tick_data = pd.read_csv('C:\\Users\\pebaqu\\Downloads\\USDJPY-2018-01.csv', parse_dates=True )
df_tick_data['TTime']=df_tick_data['TTime'].apply(lambda x: np.datetime64(datetime.datetime.strptime(x, '%Y%m%d %H:%M:%S.%f'),unit = 'ms'))

Wall time: 1min 17s


In [9]:
print(df_tick_data)

            Pair                   TTime      Bid      Ask
0        USD/JPY 2018-01-01 22:01:30.499  112.570  112.800
1        USD/JPY 2018-01-01 22:01:32.143  112.600  112.800
2        USD/JPY 2018-01-01 22:01:50.876  112.614  112.722
3        USD/JPY 2018-01-01 22:02:02.819  112.600  112.800
4        USD/JPY 2018-01-01 22:02:04.139  112.614  112.723
5        USD/JPY 2018-01-01 22:02:22.881  112.600  112.800
6        USD/JPY 2018-01-01 22:03:47.489  112.613  112.714
7        USD/JPY 2018-01-01 22:03:48.641  112.610  112.696
8        USD/JPY 2018-01-01 22:04:02.814  112.605  112.695
9        USD/JPY 2018-01-01 22:04:04.288  112.603  112.704
10       USD/JPY 2018-01-01 22:04:04.614  112.610  112.688
11       USD/JPY 2018-01-01 22:04:04.670  112.600  112.690
12       USD/JPY 2018-01-01 22:04:04.775  112.600  112.700
13       USD/JPY 2018-01-01 22:04:04.883  112.610  112.688
14       USD/JPY 2018-01-01 22:04:04.937  112.600  112.690
15       USD/JPY 2018-01-01 22:04:04.990  112.600  112.7

In [25]:
'''Array testing'''

data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)
print(data)
data

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]


array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [50]:
%%time
'''Creating empty base and final arrays'''

arr_data=df_tick_data[:100000]
#print(test_data)

arr_base_len=len(arr_data.index)
arr_final_len= (len(arr_data.index)*(len(arr_data.index)-1))//2


arr_base=np.zeros(arr_base_len, dtype={'names':('PTime','STime', 'PPrice', 'SPrice'),
                          'formats':('datetime64[ms]','datetime64[ms]', 'f8','f8')})

arr_final=np.zeros(arr_final_len, dtype={'names':('PTime','STime', 'PPrice', 'SPrice', 'Profit'),
                          'formats':('datetime64[ms]','datetime64[ms]', 'f8','f8','f8')})

#test_arr_1=np.zeros((arr_len,4))
#test_arr_1[0]


#print(test_arr_1[1][1])
#print(test_arr_1[1].shape)
#print(test_arr_1)
#test_arr_1

'''
print(test_arr.shape)

print(test_data.count)
print(test_data.shape)
print(len(test_data.index))
'''


MemoryError: 

In [45]:
%%time

'''This writes the dataframe to an array'''
for index, row in arr_data.iterrows():
    #print(index, test_data.loc[index,'TTime'])
    arr_base[index]=(arr_data.loc[index,'TTime'], arr_data.loc[index,'TTime'],arr_data.loc[index,'Bid'],arr_data.loc[index,'Bid'])
    
    #ttime = np.datetime64(datetime.datetime.strptime(str(test_data.loc[index,'TTime'])[:-3],'%Y-%m-%d %H:%M:%S.%f'),unit='ms')
    #pprice = test_data.loc[index,'Bid']
    #print(test_arr_1[index][0]) #this is the right way to get the data in an array
    #print(ttime)
    #test_arr_1[index]=(ttime,test_data.loc[index,'TTime'],pprice,test_data.loc[index,'Bid'],pprice-test_data.loc[index,'Bid'])
    #test_arr_1[index][3]=test_data.loc[index,'Bid']
print(arr_base.shape)

(10000,)
Wall time: 1.25 s


In [6]:
%%time
'''This is the final array (concat + PTime, STime, PPrice, SPrice, Profit) using individual row looping'''
y=0
total_concat_rows=0
for x in np.nditer(arr_base):
    
    first_arr=np.take(arr_base, np.where(arr_base['STime']==np.datetime64(x['STime'])))
    ptime=first_arr[0][0][0]
    pprice=first_arr[0][0][2]
    concat_array=np.take(arr_base, np.where(arr_base['STime']>np.datetime64(x['STime'])))
    concat_rows=concat_array.size
    #arr_final[0:concat_rows][0]=ptime
    #concat_array[x]=(ptime,,pprice,)
    #concat_array[0][0][0]=ptime
    ptime_index=0
    for x in range(0,concat_rows): #can i make this a lamda?
        #print(arr_final[total_concat_rows+ptime_index][2], ptime_index,x)
        arr_final[total_concat_rows+ptime_index][0]=ptime
        arr_final[total_concat_rows+ptime_index][2]=pprice
        arr_final[total_concat_rows+ptime_index][1]=concat_array[0][ptime_index][1]
        arr_final[total_concat_rows+ptime_index][3]=concat_array[0][ptime_index][3]
        arr_final[total_concat_rows+ptime_index][4]=arr_final[total_concat_rows+ptime_index][3]-arr_final[total_concat_rows+ptime_index][2]
        ptime_index=ptime_index+1
    #print(concat_array)
    #print(concat_array[0].shape)
    
    #print(concat_array[0][0][y]) #This traverses the elements causing an invalid index exception 
    #print(concat_rows)
    #print(arr_final[0:concat_rows][0][0])
    #y=y+1
    total_concat_rows=total_concat_rows+concat_rows
print(arr_final.shape)

(499500,)
Wall time: 3.45 s


In [47]:
%%time
'''Testing array column selection'''

print(type(arr_final))
print(arr_final.shape)
print(arr_final[1:5])
print(arr_final[1:5]['STime'])#This works

<class 'numpy.ndarray'>
(499500,)
[('2018-01-01T22:01:30.499', '2018-01-01T22:01:50.876', 112.57, 112.614, 0.044)
 ('2018-01-01T22:01:30.499', '2018-01-01T22:02:02.819', 112.57, 112.6  , 0.03 )
 ('2018-01-01T22:01:30.499', '2018-01-01T22:02:04.139', 112.57, 112.614, 0.044)
 ('2018-01-01T22:01:30.499', '2018-01-01T22:02:22.881', 112.57, 112.6  , 0.03 )]
['2018-01-01T22:01:50.876' '2018-01-01T22:02:02.819'
 '2018-01-01T22:02:04.139' '2018-01-01T22:02:22.881']
('2018-01-01T22:01:30.499', '2018-01-01T22:01:50.876', 112.57, 112.614, 0.044)
Wall time: 3.01 ms


In [13]:
print(arr_final)
print(arr_base)

[('1970-01-01T00:00:00.000', '1970-01-01T00:00:00.000', 0., 0., 0.)
 ('1970-01-01T00:00:00.000', '1970-01-01T00:00:00.000', 0., 0., 0.)
 ('1970-01-01T00:00:00.000', '1970-01-01T00:00:00.000', 0., 0., 0.) ...
 ('1970-01-01T00:00:00.000', '1970-01-01T00:00:00.000', 0., 0., 0.)
 ('1970-01-01T00:00:00.000', '1970-01-01T00:00:00.000', 0., 0., 0.)
 ('1970-01-01T00:00:00.000', '1970-01-01T00:00:00.000', 0., 0., 0.)]
[('2018-01-01T22:01:30.499', '2018-01-01T22:01:30.499', 112.57 , 112.57 )
 ('2018-01-01T22:01:32.143', '2018-01-01T22:01:32.143', 112.6  , 112.6  )
 ('2018-01-01T22:01:50.876', '2018-01-01T22:01:50.876', 112.614, 112.614)
 ('2018-01-01T22:02:02.819', '2018-01-01T22:02:02.819', 112.6  , 112.6  )
 ('2018-01-01T22:02:04.139', '2018-01-01T22:02:04.139', 112.614, 112.614)
 ('2018-01-01T22:02:22.881', '2018-01-01T22:02:22.881', 112.6  , 112.6  )
 ('2018-01-01T22:03:47.489', '2018-01-01T22:03:47.489', 112.613, 112.613)
 ('2018-01-01T22:03:48.641', '2018-01-01T22:03:48.641', 112.61 , 112.

In [46]:
%%time
'''This is the final array (concat + PTime, STime, PPrice, SPrice, Profit). 
This is trying to use the index logic and not go through each row'''

y=0
curr_row=0
total_concat_rows=0
for x in np.nditer(arr_base):
    
    first_arr=np.take(arr_base, np.where(arr_base['STime']==np.datetime64(x['STime'])))
    ptime=first_arr[0][0][0]
    pprice=first_arr[0][0][2]
    concat_array=np.take(arr_base, np.where(arr_base['STime']>np.datetime64(x['STime'])))
    concat_rows=concat_array.size
    total_concat_rows=total_concat_rows+concat_rows
    arr_final[curr_row:total_concat_rows]['PTime']=ptime
    arr_final[curr_row:total_concat_rows]['PPrice']=pprice
    if concat_array.shape != (1,0):
        arr_final[curr_row:total_concat_rows]['STime']=concat_array[0]['PTime']#need to get logic for concat array indexing. need to select whole column.
        arr_final[curr_row:total_concat_rows]['SPrice']=concat_array[0]['PPrice']

    curr_row=curr_row+concat_rows
    #print(concat_array)
    #print(concat_array.shape)
    #if concat_array.shape != (1,0):
    #    print("yes")
    #else:
    #    print("no")
print(arr_final)

[('2018-01-01T22:01:30.499', '2018-01-01T22:01:32.143', 112.57, 112.6  , 0.)
 ('2018-01-01T22:01:30.499', '2018-01-01T22:01:50.876', 112.57, 112.614, 0.)
 ('2018-01-01T22:01:30.499', '2018-01-01T22:02:02.819', 112.57, 112.6  , 0.)
 ...
 ('1970-01-01T00:00:00.000', '1970-01-01T00:00:00.000',   0.  ,   0.   , 0.)
 ('1970-01-01T00:00:00.000', '1970-01-01T00:00:00.000',   0.  ,   0.   , 0.)
 ('1970-01-01T00:00:00.000', '1970-01-01T00:00:00.000',   0.  ,   0.   , 0.)]
Wall time: 1.99 s


In [48]:
print(arr_final.shape)

(49995000,)


In [39]:
concat_array=np.take(arr_base, np.where(arr_base['STime']>np.datetime64(x['STime'])))
print(concat_array)
print(concat_array[0]['PTime'])
#print(arr_base)

[[('2018-01-01T22:01:32.143', '2018-01-01T22:01:32.143', 112.6  , 112.6  )
  ('2018-01-01T22:01:50.876', '2018-01-01T22:01:50.876', 112.614, 112.614)
  ('2018-01-01T22:02:02.819', '2018-01-01T22:02:02.819', 112.6  , 112.6  )
  ('2018-01-01T22:02:04.139', '2018-01-01T22:02:04.139', 112.614, 112.614)
  ('2018-01-01T22:02:22.881', '2018-01-01T22:02:22.881', 112.6  , 112.6  )
  ('2018-01-01T22:03:47.489', '2018-01-01T22:03:47.489', 112.613, 112.613)
  ('2018-01-01T22:03:48.641', '2018-01-01T22:03:48.641', 112.61 , 112.61 )
  ('2018-01-01T22:04:02.814', '2018-01-01T22:04:02.814', 112.605, 112.605)
  ('2018-01-01T22:04:04.288', '2018-01-01T22:04:04.288', 112.603, 112.603)]]
['2018-01-01T22:01:32.143' '2018-01-01T22:01:50.876'
 '2018-01-01T22:02:02.819' '2018-01-01T22:02:04.139'
 '2018-01-01T22:02:22.881' '2018-01-01T22:03:47.489'
 '2018-01-01T22:03:48.641' '2018-01-01T22:04:02.814'
 '2018-01-01T22:04:04.288']
